import os
import datetime
from pathlib import Path

import MDAnalysis as mda
import chilife as xl
import numpy as np
from scipy.constants import k as kB  # Boltzmann constant

DATA_DIR = Path(__file__).parent.parent / "data" / "rg_analysis"

# -----------------------------
# USER INPUT
# Switch to DATA_DIR / "JS_3kbar_equib.pdb" and re-run to get the 3 kbar
# condition -- this script reports one pressure condition per run.
pdb_file = DATA_DIR / "JS_1bar_equib.pdb"  # Protein PDB
temperature = 293.0  # K
viscosity = 1.002e-3  # Pa·s (water at 20 °C)
hydration_shell = 0.3  # nm
rotlib = DATA_DIR / "GTN_rotlib.npz"  # Spin label rotamer library
spin_sites = (406, 537)  # Residues to attach spin labels
# -----------------------------

# Load protein
u = mda.Universe(pdb_file)

# -----------------------------
# Assign protein masses
# -----------------------------
atomic_masses = {
    "H": 1.008,
    "C": 12.011,
    "N": 14.007,
    "O": 15.999,
    "S": 32.06,
    "P": 30.974,
    "Gd": 157.25,  # for spin label
}

# -----------------------------
# Add spin labels
# -----------------------------
G1 = xl.SpinLabel("GTN", site=spin_sites[0], protein=u, sample=5000, rotlib=rotlib)
G2 = xl.SpinLabel("GTN", site=spin_sites[1], protein=u, sample=5000, rotlib=rotlib)

# Mutate protein to include spin labels
u = xl.mutate(u, G1)
u = xl.mutate(u, G2)

# Assign masses directly
atomic_masses = {
    "H": 1.008,
    "C": 12.011,
    "N": 14.007,
    "O": 15.999,
    "S": 32.06,
    "Gd": 157.25,
}
u.add_TopologyAttr(
    "masses", np.array([atomic_masses.get(a.name[0], 12.0) for a in u.atoms])
)

# -----------------------------
# Calculate Rg, Rh, and tau_c including spin labels
# -----------------------------
protein_plus_labels = u.select_atoms("protein or resname GTN")  # include spin labels

# Radius of gyration (Å), mass-weighted for consistency with mass-weighted COM
Rg = protein_plus_labels.radius_of_gyration()
Rg_nm = Rg * 0.1  # Å → nm

# Hydrodynamic radius (dry, globular approximation)
Rh_dry_nm = Rg_nm / 0.775

# Add hydration shell
Rh_hyd_nm = Rh_dry_nm + hydration_shell

# Rotational correlation time (s)
Rh_m = Rh_hyd_nm * 1e-9  # nm → m
tau_c = (4 * np.pi * viscosity * Rh_m**3) / (3 * kB * temperature)

# -----------------------------
# Calculate Gd-Gd distance
# -----------------------------
r = np.linspace(0, 70, 256)
P_Gd = xl.distance_distribution(G1, G2, r=r)
r_nm = r * 0.1  # Å → nm
avg_dist_nm = np.sum(P_Gd * r_nm) / np.sum(P_Gd)

# -----------------------------
# Total mass (protein + labels)
# -----------------------------
total_mass_kDa = protein_plus_labels.total_mass() / 1000.0  # amu -> kDa

# -----------------------------
# Output
# -----------------------------
lines = [
    f"Radius of gyration Rg (protein + labels) : {Rg_nm:.3f} nm",
    f"Hydrodynamic radius (dry)               : {Rh_dry_nm:.3f} nm",
    f"Hydrated hydrodynamic radius            : {Rh_hyd_nm:.3f} nm",
    f"Rotational correlation time τc          : {tau_c * 1e9:.2f} ns",
    f"Average Gd-Gd distance                  : {avg_dist_nm:.3f} nm",
    f"Total mass (protein + labels)            : {total_mass_kDa:.3f} kDa",
]

for line in lines:
    print(line)

script_name = os.path.basename(__file__)
timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
output_dir = Path(__file__).parent.parent / "outputs"
output_dir.mkdir(parents=True, exist_ok=True)
output_txt = output_dir / (os.path.splitext(script_name)[0] + "_results.txt")

with open(output_txt, "w") as f:
    f.write(f"Generated by: {script_name}\n")
    f.write(f"Date/time: {timestamp}\n")
    f.write("\n")
    f.write("Results:\n")
    for line in lines:
        f.write(line + "\n")

print(f"\nResults written to {output_txt}")
